# Site settings
title: "Peter Zujko"
email: peter@zujko.xyz
description: ""
baseurl: ""
url: "localhost:4000"
title_description: "Developer &bull; Computer Science Student @ RIT"
title_image: "https://secure.gravatar.com/avatar/a4055ddbdcb86ec61d69c6c915c404cb?&size=200&default=mm&rating=pg"
disqus_account: peterzujko
github_repository: https://github.com/zujko/zujko.github.io
post_limit: 5

# Social usernames/URLs
twitter_username: PeterZujko
github_username:  zujko
linkedin_link: https://www.linkedin.com/in/zujko

# Footer
footer_center: "&lt;/&gt; on <a href=\"https://github.com/zujko/zujko.github.io\" target=\"_new\">Github</a> &nbsp;<i class=\"fa fa-github\"></i> <br> &copy; 2015 Peter Zujko <br> Licensed under the <a href=\"https://www.gnu.org/licenses/gpl-3.0.html\" target=\"_new\">The GNU General Public License v3.0</a>"
# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
